import Head from "next/head";
import Carousel from "@/components/Carousel";
import Cards from "@/components/Cards";
import CardsRight from "@/components/CardsRight";
import CardCapsule from "@/components/CardCapsule";
import { GetServerSideProps, NextPage } from "next";
import { ProductType } from "@/type/type";

interface Props {
  dataRes: ProductType[];
}

const HomePage: NextPage<Props> = ({ dataRes }) => {
  return (
    <>
      <Head>
        <title>Igralishte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CardsRight />
      <Carousel data={dataRes} />
      <Cards />
      <CardCapsule />
    </>
  );
};

export default HomePage;

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(
    `http://localhost:5001/Igralishteskopje?_start=0&_limit=3`
  );
  const dataRes: ProductType[] = await res.json();

  return {
    props: {
      dataRes: dataRes,
    },
  };
};
